services:
  # Servicio de la base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: edc_postgres_logs
    environment:
      POSTGRES_DB: edc_logs
      POSTGRES_USER: edc
      POSTGRES_PASSWORD: edc123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script para crear la tabla
      - postgres_data:/var/lib/postgresql/data             # Volumen para persistir los datos
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Herramienta de administración web para la base de datos
  adminer:
    image: adminer
    container_name: edc_adminer
    ports:
      - "8888:8080"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx # Un nombre descriptivo para tu contenedor
    ports:
      - "9876:80"
    volumes:
      - ./deployment/assets/issuer/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/assets/issuer/did.docker.json:/var/www/.well-known/did.json:ro
    restart: unless-stopped # Asegura que Nginx se reinicie si se detiene inesperadamente
volumes:
  postgres_data: